package type;

public enum TipoDocumentoReferencia {
    FACTURA_ELECTRONICA("01"),
    NOTA_DE_DEBITO_ELECTRONICA("02"),
    NOTA_DE_CREDITO_ELECTRONICA("03"),
    TIQUETE_ELECTRONICO("04"),
    NOTA_DE_DESPACHO("05"),
    CONTRATO("06"),
    PROCEDIMIENTO("07"),
    COMPROBANTE_EMITIDO_EN_CONTINGENCIA("08"),
    DEVOLUCION_MERCADERIA("09"),
    SUSTITUYE_FACTURA_RECHAZADA_POR_EL_MINISTERIO_DE_HACIENDA("10"),
    SUSTITUYE_FACTURA_RECHAZADA_POR_EL_RECEPTOR_DEL_COMPROBANTE("11"),
    SUSTITUYE_FACTURA_DE_EXPORTACION("12"),
    FACTURACION_MES_VENCIDO("13"),
    COMPROBANTE_APORTADO_POR_CONTRIBUYENTE_DEL_REGIMEN_DE_TRIBUTACION_SIMPLIFICADO("14"),
    SUSTITUYE_UNA_FACTURA_ELECTRONICA_DE_COMPRA("15"),
    OTROS("99");
    private final String value;

    TipoDocumentoReferencia(final String value){ this.value = value;}

    public String getValue(){return this.value;}
}
